apiVersion: v1
kind: Service
metadata:
  name: hello-metrics-lb
  labels:
    app: hello-metrics
spec:
  type: LoadBalancer
  selector:
    app: hello-metrics
  ports:
  - port: 80
    targetPort: 8080
